# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Aleksei_Varaksin_Tracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Aleksei_Varaksin_Tracker
  pod 'GoogleMaps', '~> 3.10.0'

end
